# Generated by Django 4.0.1 on 2022-02-14 13:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boardgame',
            name='times_played',
        ),
    ]
