# Generated by Django 4.0.1 on 2022-02-20 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boardgames', '0002_remove_boardgame_times_played'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='winner_points',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
